import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sparkles, AlertCircle, CheckCircle2, HelpCircle, RefreshCw } from "lucide-react";
import { toast } from "sonner";

interface Report {
  id: string;
  property_id: string;
  summary: string;
  highlights: string[];
  watchouts: string[];
  questions_to_ask: string[];
  created_at: string;
}

export function PropertyIntelligencePanel({ property }: { property: any }) {
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const load = async () => {
    setLoading(true);
    const { data } = await supabase
      .from("property_intelligence_reports")
      .select("*")
      .eq("property_id", property.id)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();
    setReport(data as Report | null);
    setLoading(false);
  };

  useEffect(() => {
    load();
  }, [property.id]);

  const generate = async () => {
    setGenerating(true);
    const { data, error } = await supabase.functions.invoke("property-intelligence", {
      body: { property_id: property.id },
    });
    setGenerating(false);
    if (error) {
      toast.error(error.message ?? "Failed to generate report");
      return;
    }
    if (data?.error) {
      toast.error(data.error);
      return;
    }
    toast.success("Property intelligence ready");
    setReport(data as Report);
  };

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between gap-2 space-y-0">
        <CardTitle className="text-base flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" /> AI property intelligence
        </CardTitle>
        <Button size="sm" variant={report ? "outline" : "default"} onClick={generate} disabled={generating}>
          {generating ? (
            <>Generating…</>
          ) : report ? (
            <>
              <RefreshCw className="mr-2 h-3.5 w-3.5" /> Regenerate
            </>
          ) : (
            <>
              <Sparkles className="mr-2 h-3.5 w-3.5" /> Generate report
            </>
          )}
        </Button>
      </CardHeader>
      <CardContent className="space-y-4">
        {loading ? (
          <p className="text-sm text-muted-foreground">Loading…</p>
        ) : !report ? (
          <p className="text-sm text-muted-foreground">
            Get an instant one-pager: highlights, watchouts, and the right questions to ask. Generated by Canterra AI.
          </p>
        ) : (
          <>
            <p className="text-sm leading-relaxed">{report.summary}</p>

            {report.highlights.length > 0 && (
              <Section
                icon={<CheckCircle2 className="h-4 w-4 text-primary" />}
                title="Highlights"
                items={report.highlights}
              />
            )}
            {report.watchouts.length > 0 && (
              <Section
                icon={<AlertCircle className="h-4 w-4 text-destructive" />}
                title="Watchouts"
                items={report.watchouts}
              />
            )}
            {report.questions_to_ask.length > 0 && (
              <Section
                icon={<HelpCircle className="h-4 w-4 text-muted-foreground" />}
                title="Questions to ask"
                items={report.questions_to_ask}
              />
            )}
            <p className="text-[10px] text-muted-foreground pt-2 border-t">
              Generated {new Date(report.created_at).toLocaleString()} · AI-assisted, verify with your agent.
            </p>
          </>
        )}
      </CardContent>
    </Card>
  );
}

const Section = ({ icon, title, items }: { icon: React.ReactNode; title: string; items: string[] }) => (
  <div>
    <h4 className="font-medium text-xs uppercase tracking-wider text-primary mb-2 flex items-center gap-1.5">
      {icon} {title}
    </h4>
    <ul className="space-y-1.5">
      {items.map((it, i) => (
        <li key={i} className="text-sm flex items-start gap-2">
          <span className="text-muted-foreground mt-1">•</span>
          <span>{it}</span>
        </li>
      ))}
    </ul>
  </div>
);
